RENAME TABLE `box_cache`.`cache` TO `box_cache`.`victor_cache`;
RENAME TABLE `box_cache`.`cache_admin_menu` TO `box_cache`.`victor_cache_admin_menu`;
RENAME TABLE `box_cache`.`cache_block` TO `box_cache`.`victor_cache_block`;
RENAME TABLE `box_cache`.`cache_bootstrap` TO `box_cache`.`victor_cache_bootstrap`;
RENAME TABLE `box_cache`.`cache_browscap` TO `box_cache`.`victor_cache_browscap`;
RENAME TABLE `box_cache`.`cache_coder` TO `box_cache`.`victor_cache_coder`;
RENAME TABLE `box_cache`.`cache_field` TO `box_cache`.`victor_cache_field`;
RENAME TABLE `box_cache`.`cache_filter` TO `box_cache`.`victor_cache_filter`;
RENAME TABLE `box_cache`.`cache_form` TO `box_cache`.`victor_cache_form`;
RENAME TABLE `box_cache`.`cache_image` TO `box_cache`.`victor_cache_image`;
RENAME TABLE `box_cache`.`cache_libraries` TO `box_cache`.`victor_cache_libraries`;
RENAME TABLE `box_cache`.`cache_menu` TO `box_cache`.`victor_cache_menu`;
RENAME TABLE `box_cache`.`cache_page` TO `box_cache`.`victor_cache_page`;
RENAME TABLE `box_cache`.`cache_path` TO `box_cache`.`victor_cache_path`;
RENAME TABLE `box_cache`.`cache_rules` TO `box_cache`.`victor_cache_rules`;
RENAME TABLE `box_cache`.`cache_tmgmt` TO `box_cache`.`victor_cache_tmgmt`;
RENAME TABLE `box_cache`.`cache_token` TO `box_cache`.`victor_cache_token`;
RENAME TABLE `box_cache`.`cache_update` TO `box_cache`.`victor_cache_update`;
RENAME TABLE `box_cache`.`cache_variable` TO `box_cache`.`victor_cache_variable`;
RENAME TABLE `box_cache`.`cache_views` TO `box_cache`.`victor_cache_views`;
RENAME TABLE `box_cache`.`cache_views_data` TO `box_cache`.`victor_cache_views_data`;
RENAME TABLE `box_cache`.`sessions` TO `box_cache`.`victor_sessions`;
RENAME TABLE `box_cache`.`watchdog` TO `box_cache`.`victor_watchdog`;



TRUNCATE TABLE `box`.`cache`; 
TRUNCATE TABLE `box`.`cache_admin_menu`; 
TRUNCATE TABLE `box`.`cache_block`; 
TRUNCATE TABLE `box`.`cache_bootstrap`; 
TRUNCATE TABLE `box`.`cache_browscap`; 
TRUNCATE TABLE `box`.`cache_coder`; 
TRUNCATE TABLE `box`.`cache_field`; 
TRUNCATE TABLE `box`.`cache_filter`; 
TRUNCATE TABLE `box`.`cache_form`; 
TRUNCATE TABLE `box`.`cache_image`; 
TRUNCATE TABLE `box`.`cache_libraries`; 
TRUNCATE TABLE `box`.`cache_menu`; 
TRUNCATE TABLE `box`.`cache_page`; 
TRUNCATE TABLE `box`.`cache_path`; 
TRUNCATE TABLE `box`.`cache_rules`; 
TRUNCATE TABLE `box`.`cache_tmgmt`; 
TRUNCATE TABLE `box`.`cache_token`; 
TRUNCATE TABLE `box`.`cache_update`; 
TRUNCATE TABLE `box`.`cache_variable`; 
TRUNCATE TABLE `box`.`cache_views`; 
TRUNCATE TABLE `box`.`cache_views_data`; 
TRUNCATE TABLE `box`.`sessions`;
TRUNCATE TABLE `box`.`watchdog`; 


TRUNCATE TABLE `boxcom`.`cache`; 
TRUNCATE TABLE `boxcom`.`cache_admin_menu`; 
TRUNCATE TABLE `boxcom`.`cache_block`; 
TRUNCATE TABLE `boxcom`.`cache_bootstrap`; 
TRUNCATE TABLE `boxcom`.`cache_browscap`; 
TRUNCATE TABLE `boxcom`.`cache_coder`; 
TRUNCATE TABLE `boxcom`.`cache_field`; 
TRUNCATE TABLE `boxcom`.`cache_filter`; 
TRUNCATE TABLE `boxcom`.`cache_form`; 
TRUNCATE TABLE `boxcom`.`cache_image`; 
TRUNCATE TABLE `boxcom`.`cache_libraries`; 
TRUNCATE TABLE `boxcom`.`cache_menu`; 
TRUNCATE TABLE `boxcom`.`cache_page`; 
TRUNCATE TABLE `boxcom`.`cache_path`; 
TRUNCATE TABLE `boxcom`.`cache_rules`; 
TRUNCATE TABLE `boxcom`.`cache_tmgmt`; 
TRUNCATE TABLE `boxcom`.`cache_token`; 
TRUNCATE TABLE `boxcom`.`cache_update`; 
TRUNCATE TABLE `boxcom`.`cache_variable`; 
TRUNCATE TABLE `boxcom`.`cache_views`; 
TRUNCATE TABLE `boxcom`.`cache_views_data`; 
TRUNCATE TABLE `boxcom`.`sessions`;
TRUNCATE TABLE `boxcom`.`watchdog`; 
